/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StaffManageStationD.java
 *
 * Created on 2012-4-25, 19:10:56
 */

package carparkaplication.UI;

import carparkaplication.CODE.Staff;
import org.jdesktop.application.Action;

/**
 *
 * @author Administrator
 */
public class StaffManageStationD extends javax.swing.JDialog {

    public Main theMainFrame;
    /** Creates new form StaffManageStationD */
    public StaffManageStationD(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        apply_button.setText("Apply Now");
        applacationstatusbutton.setText("Application Status");
        monthbill_button.setText("Monthly Bill");
        edit_account_button.setText("Edit Account");
        theMainFrame=(Main)parent;
       staff_number_text.setText(((Staff)theMainFrame.theUser).getStaff_number());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        depart_item = new javax.swing.JComboBox();
        staff_number_text = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        apply_button = new javax.swing.JButton();
        monthbill_button = new javax.swing.JButton();
        plage_number_text = new javax.swing.JTextField();
        applacationstatusbutton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        edit_account_button = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        depart_item.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "EECS", "Financial", "Math" }));
        depart_item.setName("depart_item"); // NOI18N

        staff_number_text.setName("staff_number_text"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(carparkaplication.CarParkAplicationApp.class).getContext().getResourceMap(StaffManageStationD.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(carparkaplication.CarParkAplicationApp.class).getContext().getActionMap(StaffManageStationD.class, this);
        apply_button.setAction(actionMap.get("applay_button_clicked")); // NOI18N
        apply_button.setText(resourceMap.getString("apply_button.text")); // NOI18N
        apply_button.setName("apply_button"); // NOI18N

        monthbill_button.setAction(actionMap.get("monthlybill_button_clicked")); // NOI18N
        monthbill_button.setText(resourceMap.getString("monthbill_button.text")); // NOI18N
        monthbill_button.setName("monthbill_button"); // NOI18N

        plage_number_text.setName("plage_number_text"); // NOI18N

        applacationstatusbutton.setAction(actionMap.get("getStatus_button_clicked")); // NOI18N
        applacationstatusbutton.setText(resourceMap.getString("applacationstatusbutton.text")); // NOI18N
        applacationstatusbutton.setName("applacationstatusbutton"); // NOI18N

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setName("jSeparator1"); // NOI18N

        edit_account_button.setAction(actionMap.get("edit_account_btn_clicked")); // NOI18N
        edit_account_button.setText(resourceMap.getString("edit_account_button.text")); // NOI18N
        edit_account_button.setName("edit_account_button"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(apply_button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(applacationstatusbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(monthbill_button, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(edit_account_button, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(plage_number_text)
                        .addComponent(staff_number_text, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                    .addComponent(depart_item, 0, 163, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(apply_button, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(applacationstatusbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(monthbill_button, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(edit_account_button, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(staff_number_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depart_item, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plage_number_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                StaffManageStationD dialog = new StaffManageStationD(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    @Action
    public void applay_button_clicked() {
        String staff_number=staff_number_text.getText().toString();
        String department=depart_item.getSelectedItem().toString();
        String platenumber=plage_number_text.getText().toString();
        MessageDialog myMessageDialog=new MessageDialog(theMainFrame, rootPaneCheckingEnabled);
        if(((Staff)theMainFrame.theUser).setPlate(staff_number, department, platenumber))
        {
            myMessageDialog.setMessage("Submit success!");
        }else{
             myMessageDialog.setMessage("An error occur");
        }
        myMessageDialog.setVisible(true);
    }

    @Action
    public void getStatus_button_clicked() {
        String status=((Staff)theMainFrame.theUser).theCarPark_Control.getStaffStatus(((Staff)theMainFrame.theUser).getStaff_number());
        MessageDialog myMessageDialog=new MessageDialog(theMainFrame, rootPaneCheckingEnabled);
        myMessageDialog.setMessage(status);
        myMessageDialog.setVisible(true);
    }

    @Action
    public void monthlybill_button_clicked() {
        StaffMonthBillD myStaffMonthBillD=new StaffMonthBillD(theMainFrame, rootPaneCheckingEnabled);
        myStaffMonthBillD.setVisible(true);
    }

    @Action
    public void edit_account_btn_clicked() {
        ChangethestaffpasswordD myChangethestaffpasswordD=new ChangethestaffpasswordD(theMainFrame, rootPaneCheckingEnabled);
        myChangethestaffpasswordD.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applacationstatusbutton;
    private javax.swing.JButton apply_button;
    private javax.swing.JComboBox depart_item;
    private javax.swing.JButton edit_account_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton monthbill_button;
    private javax.swing.JTextField plage_number_text;
    private javax.swing.JTextField staff_number_text;
    // End of variables declaration//GEN-END:variables

}
